### ISSUE TITLE
chrome-new-tab-url doesn't redirect to local files

### ISSUE THREAD

**Issue by philc** [smblott-github/chrome-new-tab-url#8]
I'd like to set the redirect page to `file:///new_tab_page.html`. This avoids having to contact the network, and I can put whatever I want in that file.

Loading this file works if you navigate to it using Chrome's Omnibar. However, configuring chrome-new-tab-url with this URL results in this error when a new tab is opened:

`Not allowed to load local resource: file:///new_tab_page.html`. After some light googling this may be unfixable. If true, it's worth noting this limitation in the extension's settings page or at least in the README.

**Comment by smblott-github** [comment]
@philc... This is fixed in version 1.0.2 (which I just pushed to the Chrome Store): f3706f0d9a4cb8f539d31a1eccabe25fcf9752a3.

Thanks for the input.

**Comment by smblott-github** [comment]
Select *Allow access to file URLs* on the extensions page.

**Comment by wrpoulson** [comment]
@smblott-github This is still not working for me in 1.0.2 with the option enabled. I can not navigate to a file path that is pasted into Chrome itself works fine.
